### ISSUE TITLE
Emulator broken with "Missing Header" error message

### ISSUE THREAD

**Issue by stmcginnis** [SNIA/Swordfish-API-Emulator#123]
## Description

Like the Redfish emulator it builds on, you should be able to install requirements and run the emulator, then browse to the endpoint and view the UI explorer for the emulator. This currently works when just using the Redfish emulator, but breaks with the current Swordfish emulator is added with the error message "Missing Header" printed to the browser and the console debug output.

This appears to be due to a check added for authentication: https://github.com/SNIA/Swordfish-API-Emulator/blob/master/api_emulator/utils.py#L349

Looks like this was [added a little while back](https://github.com/SNIA/Swordfish-API-Emulator/commit/d10270517990ae78be93fa502a115135a390bdad#diff-7bc736601a8a3ae6e8065211cfe224b36578ec4af9f5008d6937c60cb2d0a558). There is no corresponding check on the Redfish side, and it is not obvious what one should do when just running the emulator locally to explore the API.

## Expectation

A user should be able to clone the repo, run the `setup.sh` script, and open a browser to view the API.

**Comment by rahlvers** [comment]
The "Missing Header" message is a supplemental message to the 403 Forbidden return; the 403 indicates that you have not used appropriate credentials for this URI.

**Comment by rahlvers** [comment]
Either create a Session or use the Basic Auth (username / password) to the URI and you won't get the 403 return.

**Comment by rahlvers** [comment]
To clarify:  the emulator, as instantiated from setup.sh (with sessions / security enabled), follows the Redfish specification:

Redfish resources shall not be available as unauthenticated, except for:

- The service root to identify the device and service locations.  (/redfish/v1)
- The Redfish metadata document to get resource types. (/redfish/v1/$metadata)
- The OData service document for compatibility with OData clients.  (/redfish/v1/odata)
- The Redfish OpenAPI YAML document for compatibility with OpenAPI clients. (not implemented at this time)
- The version object at /redfish
