### ISSUE TITLE
Installation instructions need enhancements

### ISSUE THREAD

**Issue by rahlvers** [SNIA/Swordfish-API-Emulator#15]
Add directions to include what to do with all files in repository:
*  Resources directory
*  What to do with static / mockups?  Won't build / run with current instructions
....

**Comment by chandramouli12** [comment]
Done.

**Comment by patrickstrick** [comment]
It doesn't look like the associated pull request addresses the two bullets rahlvers called out.

**Comment by chandramouli12** [comment]
resource directory consists of Static and Dynamic mockups.
Static Mockups( Chassis, StorageSystems and Systems) wont be effected with code .
Dynamic Mockups( Storage Services) will effect when we do any changes while running the code.

**Comment by ddeel** [comment]
Pull Request #23 addresses this Issue.
