### ISSUE TITLE
resource_manager.py not based on latest version of Redfish_Interface_Emulator file

### ISSUE THREAD

**Issue by rahlvers** [SNIA/Swordfish-API-Emulator#16]
Multiple issues:
1. need to update this file to be in sync with latest Redfish version of this file.
2. need to ensure this file has no compile errors on Windows / python 3.5 systems (multiple issues in this version)
3. Need to address multiple copyright issue. Need to end up with joint copyright.  (@ddeel)
4. Need a long-term plan to update this file when creating a swordfish instance of an emulator (what happens the next time the Redfish file is updated?)

Same / similar issues for utils.py.

**Comment by chandramouli12** [comment]
We updated resource manager file to work with latest Redfish Emulator.

**Comment by jcleung5549** [comment]
FYI - Today, that file will be updated again in the DMTF Tools TF. There change resolves SNIA's request to specify the loading for Redfish and Swordfish models.

**Comment by ddeel** [comment]
This has been corrected, and this Issue can be closed.

**Comment by rahlvers** [comment]
Closed by #21
