### ISSUE TITLE
Modify installation process to leave files in ./api_emulator/swordfish directory

### ISSUE THREAD

**Issue by rahlvers** [SNIA/Swordfish-API-Emulator#17]
Instead of moving files into ./api_emulator/redfish directory, can we put the files into the ./api_emulator/swordfish directory?  This would give a ./api_emulator directory with both a /redfish and /swordfish subdirectories.

What are the implications here? This would initially involve separating the template and api files.  
Do any other files need to go in the swordfish subdirectories?

**Comment by rahlvers** [comment]
Change references to the template and api file "includes" in resource_manager.py

**Comment by chandramouli12** [comment]
If we put both directories (i.e Swordfish and Redfish)  we have to change Resourcemanager.py and may be we have to change emulator.py file. 
I will check it and update on this.

**Comment by ddeel** [comment]
This has been done, and this Issue can be closed.
