### ISSUE TITLE
Redfish interface emulator to add flag to resource emulator to check for Swordfish

### ISSUE THREAD

**Issue by rahlvers** [SNIA/Swordfish-API-Emulator#18]
When available, separate swordfish includes by this flag.

Then, move Swordfish funcitonality into a separate file - swordfish_resource_emulator.py

Ensure changes for utils.py as well.

**Comment by ddeel** [comment]
This Issue is still pending, and needs to be worked on with the DMTF.

**Comment by ddeel** [comment]
This Issue is still pending. The flag has been added to the Redfish Interface Emulator, but it is not yet being used to separate Swordfish includes, so it is still necessary to modify the resource_manager.py and utils.py files.

**Comment by rahlvers** [comment]
Documentation for Redfish has been updated to point to Swordfish API Emulator as a superset of the Redfish emulator functionality.
