### ISSUE TITLE
Additional documentation is needed

### ISSUE THREAD

**Issue by ddeel** [SNIA/Swordfish-API-Emulator#25]
Three things need to be documented:
(1) How to install the code
(2) How to use the code
(3) How the code works

(1) seems to be done. This is taken care of by the README file (recently updated by SNIA) and the current contents of the "Swordfish Documentation" Word file.

(2) still needs to be documented. This could be a simple reference to the DMTF Redfish Interface Emulator documentation, since using the Swordfish API Emulator is very much like using the Redfish Interface Emulator.

(3) still needs to be documented. This needs to be sufficient to allow other developers to work with the Swordfish API Emulator code. It could be partly a reference to the DMTF Redfish Interface Emulator documentation, but there are also differences from how the DMTF Redfish Interface Emulator works, and these differences need to be documented.

An example of such a difference: The Swordfish API Emulator code seems to build and persist Swordfish objects in the top-level "Resources" folder, but the Redfish Interface Emulator does not do this for Redfish objects. Anything like this must be clearly documented so that other developers can see and understand how the code works.

**Comment by ddeel** [comment]
A new branch based upon master should be created for the work on updating the documentation files.

It looks like some documentation updates were done in the old Swordfish-27-4-18 branch, but that branch was out of sync with master before the most recent documentation changes were made, so it is difficult to see the changes there,

**Comment by ddeel** [comment]
This Issue remains open until the documentation is completed.

**Comment by rahlvers** [comment]
Fixed by #36
