### ISSUE TITLE
DELETE gives different results for Redfish resources and Swordfish resources

### ISSUE THREAD

**Issue by ddeel** [SNIA/Swordfish-API-Emulator#32]
The emulator responds to DELETE operations on items in Redfish collections (Chassis, Managers, Systems, etc) with a "200 OK" and the Redfish resource is deleted. This is the expected response.

The emulator responds to DELETE operations on items in Swordfish collections (StorageServices or StorageServers) with a "500 INTERNAL SERVER ERROR" and the Swordfish resource is not deleted. This is not the expected response.

The emulator response to DELETE operations needs to be the same for both Redfish resources and Swordfish resources.

This issue can be reproduced by using a REST tool (such as the Restlet Client or the Advanced REST Client) with the Swordfish API Emulator running in its default configuration.

**Comment by chandramouli12** [comment]
In Redfish "Delete"operation responds by  passing "ID" to delete an item in redfish collection.
In Swordfish emulator we are deleting members" @odata.id " to delete an item. we are passing request body to delete a member,as shown in below screens.

![image1](https://user-images.githubusercontent.com/33828560/40040089-6f827214-5836-11e8-91c9-f02181d4e765.PNG)

Now we are trying to delete item 13 from members.we are passing @odata.id in request body.

![image2](https://user-images.githubusercontent.com/33828560/40040090-6fade48a-5836-11e8-8e51-8ae9a1a1a1a7.PNG)

The response shows 200 ok status code with updated members count.
 
![image3](https://user-images.githubusercontent.com/33828560/40040091-6fd829b6-5836-11e8-8125-9eb81cd5fd8a.PNG)

**Comment by ddeel** [comment]
Swordfish is defined to be a seamless extension of Redfish, and this means that all REST operations on Swordfish resources must be done the same way that they are done on Redfish resources. There should not be any differences.

The DELETE operation in the example above should have  been done this way:
DELETE localhost:5000/redfish/v1/StorageServices/13

**Comment by rahlvers** [comment]
See #34
