### ISSUE TITLE
Respond to comments embedded in developer documentation

### ISSUE THREAD

**Issue by rahlvers** [SNIA/Swordfish-API-Emulator#37]
See comments in developer word doc in SNIA-Doc branch (committed 6/6/18 2:38 pm MT)

**Comment by ddeel** [comment]
This Issue remains open until the documentation is completed.

**Comment by rahlvers** [comment]
Outstanding comments still only in developer doc.  Install and user's guide look OK.

**Comment by rahlvers** [comment]
Fixed by #36
