### ISSUE TITLE
PATCH fails to update properties in members of Swordfish collections

### ISSUE THREAD

**Issue by ddeel** [SNIA/Swordfish-API-Emulator#38]
The master branch of the Redfish Interface Emulator has been updated to fix the PATCH issues.

When the Swordfish API Emulator is built using this updated Redfish Interface Emulator code, PATCH operations are able to correctly update the properties of dynamic Redfish objects in Redfish collections like Chassis, Managers, Systems, etc.

As an example, the following RESTful command successfully updates the "Name" property of a member of a Redfish Chassis collection:
    Command:  PATCH http://localhost:5000/redfish/v1/Chassis/Chassis-1
    Body:          { "Name": "Different Name" }

Similar PATCH commands can be used to successfully update the properties of any dynamic member of any Redfish collection.

However, similar PATCH commands fail to update the properties of dynamic members of Swordfish collections.

Here is an example of what happens when the following PATCH command tries to update a member of a Swordfish collection:
    Command:  PATCH http://localhost:5000/redfish/v1/StorageServices/1
    Body:          { "Name": "Different Name" }

The Swordfish API Emulator gets a 500 Internal Server Error, and the following errors are printed out on the console:

ERROR:flask.app:Exception on /redfish/v1/StorageServices/1 [PATCH]
Traceback (most recent call last):
  File "C:\Users\ddon\Documents\SAE180621\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ddon\Documents\SAE180621\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ddon\Documents\SAE180621\lib\site-packages\flask_restful\__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\ddon\Documents\SAE180621\lib\site-packages\flask\views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\ddon\Documents\SAE180621\lib\site-packages\flask_restful\__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
TypeError: patch() got an unexpected keyword argument 'storage_service'

**Comment by rahlvers** [comment]
Fixed by ##40
