### ISSUE TITLE
Fails to report a 405 "Method not allowed" error situation

### ISSUE THREAD

**Issue by ddeel** [SNIA/Swordfish-API-Emulator#44]
The client appears to make a change (one that cannot succeed), and fails to report a 405 "Method Not Allowed" error situation.

Here is a sequence that shows the issue. The images below are from the current versions of the client and the emulator.

Initial state; shows the StorageServices collection:
![image](https://user-images.githubusercontent.com/16329575/42646590-29a8cfce-85b6-11e8-9ef1-1698391bc104.png)

Editing the collection "Name" property to say "ChangedName":
![image](https://user-images.githubusercontent.com/16329575/42646667-66c821ac-85b6-11e8-9022-0ea065f45260.png)

The change appears to have been accepted without any error after clicking on the Save icon:
![image](https://user-images.githubusercontent.com/16329575/42646707-8878e070-85b6-11e8-9f06-d712f4b8042d.png)

Clicking on a different resource (Chassis):
![image](https://user-images.githubusercontent.com/16329575/42646787-c94b6afa-85b6-11e8-8608-8683df1b88ca.png)

Go back to StorageServices and see that the collection's Name property was not actually changed, because it now says "Storage Service Collection" again, instead of "ChangedName":
![image](https://user-images.githubusercontent.com/16329575/42646888-0cf4380e-85b7-11e8-830c-fc7c5d77edbb.png)

This is what happens when the Chrome Restlet tool is used to attempt to PATCH the Name property on the StorageServices collection:
![image](https://user-images.githubusercontent.com/16329575/42647043-93ba95a4-85b7-11e8-804c-071d1e327562.png)

The issue is that the client is not reporting the 405 "Method Not Allowed" error, and it looks like the operation succeeded, when it has actually failed. The user only discovers the problem by going to a different resource (like Chassis) and then returning to the StorageServices collection.

Note that the client shows this same behavior this for ALL of the Redfish and Swordfish collections, not just the StorageServices collection.

**Comment by rahlvers** [comment]
This issue should be logged to the basic web client rather than to the emulator.

**Comment by ddeel** [comment]
This issue was mistakenly entered here for the Swordfish API Emulator, when it is actually an issue for the Swordfish Basic Web Client. The issue has now been entered in the proper place, and is being closed here.
