### ISSUE TITLE
PATCH does not work with Swordfish objects

### ISSUE THREAD

**Issue by ddeel** [SNIA/Swordfish-API-Emulator#46]
PATCH does not work with Swordfish objects, but PATCH does work with Redfish objects.

PATCH on a Swordfish StorageServices object fails with a 405 Method Not Allowed error:
![image](https://user-images.githubusercontent.com/16329575/43227528-cf76536a-9013-11e8-82df-f2d5c2779820.png)

PATCH on a Redfish Chassis succeeds with a 200 OK status:
![image](https://user-images.githubusercontent.com/16329575/43227670-3ac888ae-9014-11e8-9cfd-3986b20aac6f.png)

**Comment by rahlvers** [comment]
Fixed in #47
