### ISSUE TITLE
Correct URL for SNIA CLA

### ISSUE THREAD

**Issue by TAHCO** [SNIA/Swordfish-API-Emulator#51]
Correct url in the text below:
Contributors that are not SNIA members must first agree to the terms of the SNIA Contributor Agreement for Non-Members: www.snia.org/cla    [https://github.com/SNIA/Swordfish-API-Emulator/blob/master/www.snia.org/cla]

**Comment by TAHCO** [comment]
Correct URL

**Comment by ddeel** [comment]
Is this a problem? The link goes to the correct place on the SNIA web site (not GitHub).
