### ISSUE TITLE
Need to resync resource_manager.py with the Redfish Interface Emulator

### ISSUE THREAD

**Issue by ddeel** [SNIA/Swordfish-API-Emulator#61]
The Swordfish API Emulator uses modified versions of the resource_manager.py and utils.py files in the Redfish Interface Emulator. Whenever these files change in the Redfish Interface Emulator, they also need to be updated in the Swordfish API Emulator.

The Redfish Interface Emulator resource_manager.py file was recently updated by @stmcginnis  to correct a problem where service root references were under the Links property instead of being direct properties of the ServiceRoot object.
- See: https://github.com/DMTF/Redfish-Interface-Emulator/issues/67
- See: https://github.com/DMTF/Redfish-Interface-Emulator/pull/68

The Swordfish API Emulator version of resource_manager.py needs to be updated with the same changes.

**Comment by rahlvers** [comment]
Fixed in #62
