### ISSUE TITLE
Python *.pyc files should be removed

### ISSUE THREAD

**Issue by jcleung5549** [SNIA/Swordfish-API-Emulator#8]
In the root directory (*.pyc) files exist.  There may be others in the sub-directories - I didn't do an exhaustive search.

**Comment by rahlvers** [comment]
Agree. @chandramouli12, please search and remove any .pyc files from your branch.

**Comment by jcleung5549** [comment]
There are more *.pyc files in ./swordfish

**Comment by chandramouli12** [comment]
removed *.pyc files

**Comment by rahlvers** [comment]
Fixed.
