### ISSUE TITLE
Enhancement needed: POST to collections to add resources

### ISSUE THREAD

**Issue by rahlvers** [SNIA/Swordfish-API-Emulator#83]
Current implementation requires POST to a new object, rather than POST to a collection to create an object (which is the RF defined behavior).

This could be resolved with enhancements to the POST function on the collections - right now, it is used to create a collection if none exists. But this could be extended to call the object POST. (Probably should be integrated together, and update the POST on the object to behavior consistent with the Redfish spec.

**Comment by rahlvers** [comment]
Note that RF spec also specifies that POST should support post to Collection/Members as well as POST to Collection

**Comment by reeya52** [comment]
POST to add resource-related CTP issues are REQ_POST_CREATE_NOT_IDEMPOTENT and REQ_POST_CREATE_TO_MEMBERS_PROP

**Comment by rahlvers** [comment]
Fixed in #92
