### ISSUE TITLE
Add support for Basic Auth

### ISSUE THREAD

**Issue by rahlvers** [SNIA/Swordfish-API-Emulator#87]

**Comment by reeya52** [comment]
Below are the CTP issue related to Basic authentication implementation:
SEC_BASIC_AUTH_STANDALONE
SEC_BOTH_AUTH_TYPES
SEC_SUPPORT_BASIC_AUTH
SEC_READ_REQUIRES_AUTH

**Comment by rahlvers** [comment]
Fixed in #92
