### ISSUE TITLE
Add support for Sessions 

### ISSUE THREAD

**Issue by rahlvers** [SNIA/Swordfish-API-Emulator#88]
Include support for Session Service - see details in redfish spec.

This requires support for https.

**Comment by reeya52** [comment]
Below are the CTP issue related to session service implementation:
SEC_REQUIRE_LOGIN_SESSIONS
SEC_BOTH_AUTH_TYPES
SEC_NO_AUTH_COOKIES
REQ_POST_CREATE_URI_IN_LOCATION_HDR
RESP_HEADERS_LOCATION
SEC_NO_PRIV_INFO_IN_MSGS
SEC_READ_REQUIRES_AUTH
SEC_REQUIRE_LOGIN_SESSIONS
SEC_SESSION_POST_RESPONSE
SEC_WRITE_REQUIRES_AUTH

**Comment by rahlvers** [comment]
Fixed in #92
