### ISSUE TITLE
Location of Swordfish resource code

### ISSUE THREAD

**Issue by jcleung5549** [SNIA/Swordfish-API-Emulator#9]
The Python files for the Swordfish have been placed in ./api_emulator/redfish.  The plan was to put the files in ./api_emulator/swordfish.

Not a biggy, but was there a reason for deviating from the plan?

**Comment by rahlvers** [comment]
Please move to ./api_emulator/swordfish so that we can clearly differentiate redfish emulator files from swordfish emulator files.

**Comment by rahlvers** [comment]
@jcleung5549 Separate but related question - we have instrumented drive in this group; should that be checked in to the redfish emulator github instead of this repo, or put in the ./api_emulator/redfish directory here?

**Comment by jcleung5549** [comment]
That is a tricky question.
- If the dynamic code for drive exists ./redfish, I would hesitant about overwriting it, less you break existing code that depends the older version
- If the dynamic code for drive is placed in ./swordfish, you'll have two versions of the drive emulation.

I would opt for ./swordfish.

**Comment by chandramouli12** [comment]
Moved the files from ./api_emulator/redfish directory to  ./api_emulator/swordfish directory. 
please revirew.

**Comment by rahlvers** [comment]
Fixed.
