### ISSUE TITLE
Add support for Roles.

### ISSUE THREAD

**Issue by rahlvers** [SNIA/Swordfish-API-Emulator#90]
This is a pre-requisite for authentication - both Basic Auth and Sessions.

**Comment by reeya52** [comment]
Role implementation has the below issue in CTP testing:
SEC_PRIV_SUPPORT_PREDEFINED_ROLES - failing because of cookie issue
SEC_PRIV_PREDEFINED_ROLE_NOT_MODIFIABLE - This has been resolved

**Comment by rahlvers** [comment]
Fixed in #92
