### ISSUE TITLE
Support to required headers

### ISSUE THREAD

**Issue by reeya52** [SNIA/Swordfish-API-Emulator#93]
Following are the CTP test issues related to headers:
RESP_HEADERS_CONTENT_TYPE
REQ_HEADERS_ODATA_VERSION
RESP_HEADERS_ALLOW_GET_OR_HEAD
RESP_HEADERS_CACHE_CONTROL
RESP_HEADERS_LINK_REL_DESCRIBED_BY
RESP_HEADERS_ALLOW_METHOD_NOT_ALLOWED

**Comment by rahlvers** [comment]
Fixed in #92
