### ISSUE TITLE
flask_login, jwt missing from pip deps

### ISSUE THREAD

**Issue by tmakatos** [SNIA/Swordfish-API-Emulator#96]

**Comment by rahlvers** [comment]
What OS are you running?  (Current requirements.txt working on Ubuntu 20.x)

**Comment by tmakatos** [comment]
I'm on  CentOS 7.9. I do see `PyJWT` and `PyJWT` in https://github.com/SNIA/Swordfish-API-Emulator/blob/master/requirements.txt, though not sure why only some of those the dependencies are mentioned in README.
